# Generated by Django 5.1.2 on 2024-11-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Earthmaiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropdownItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
