# Generated by Django 5.1.2 on 2024-11-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Earthmaiapp', '0002_dropdownitem_alter_project_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagepath', models.ImageField(default='', upload_to='images/Tree/')),
            ],
        ),
        migrations.DeleteModel(
            name='DropdownItem',
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='project',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
