# Generated by Django 5.1.2 on 2024-11-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Earthmaiapp', '0003_galleryimage_delete_dropdownitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
