# Generated by Django 5.1.2 on 2024-11-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Earthmaiapp', '0004_galleryimage_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeachImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('imagepath', models.ImageField(default='', upload_to='images/Beach/')),
            ],
        ),
        migrations.CreateModel(
            name='SocialImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('imagepath', models.ImageField(default='', upload_to='images/Social/')),
            ],
        ),
    ]
