# Generated by Django 5.1.2 on 2024-11-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Earthmaiapp', '0005_beachimage_socialimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('imagepath', models.ImageField(default='', upload_to='images/about/')),
                ('extra_info', models.CharField(default='', max_length=100, null=True)),
            ],
        ),
    ]
