# Generated by Django 5.1.2 on 2024-11-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Earthmaiapp', '0006_aboutcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutcard',
            name='extra_info',
        ),
        migrations.AddField(
            model_name='aboutcard',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
