# Generated by Django 5.1.2 on 2024-11-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Earthmaiapp', '0007_remove_aboutcard_extra_info_aboutcard_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('imagepath', models.ImageField(upload_to='images/advisor/')),
            ],
        ),
    ]
