# Generated by Django 5.1.2 on 2024-11-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Earthmaiapp', '0009_initiative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='imagepath',
            field=models.ImageField(default='', upload_to='images/advisor/'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='imagepath',
            field=models.ImageField(default='', upload_to='images/initiatives/'),
        ),
    ]
