# Generated by Django 5.1.2 on 2024-11-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Earthmaiapp', '0010_alter_advisor_imagepath_alter_initiative_imagepath'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvolvementOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('button_text', models.CharField(default='Learn More', max_length=50)),
                ('button_class', models.CharField(default='btn-primary', max_length=20)),
            ],
        ),
    ]
